# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Pim Oomen
title: Cardiac Biomechanician
email: pim@virginia.edu
# website: 

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: pim_oomen
github_username:  PimOomen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: pimjoomen
linkedin_username: pimoomen90
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#vadditional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Pim and I am a biomedical engineer specializing in cardiac biomechanics. As well as improving patient healthcare through personalized therapies I am equally passionate about training a new generation of diverse engineers to solve medical problems for years to come. I am currently a postdoctoral researcher at the University of Virginia.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Virtual heart failure treatment planning
        # link: 
        # link_text: Project Website
        additional_links:
          - title:  CardioGrowth Code
            icon: fab fa-github
            url: https://PimOomen.github.io/CardioGrowth/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          When engineers and clinicians work together, everyone benefits.
        description: | # this will include new lines to allow paragraphs
          The heart beats over 2 billion times during a human life to pump blood around the body. 
          Yet, this essential function can be cut short by diseases such as valve disease and high blood pressure. These diseases lead to changes in size and shape of the heart, ultimately resulting in heart failure.
          While many excellent treatments are available to patients nowadays, it comes as no surprise that these therapies could lead to very different outcomes when applied to different patients.
          After all, every individual is unique.
          In this projects, I am working closely with cardiologists to improve and develop personalized heart failure therapies by developing fast computer models 
          to predict how a patient's heart changes in size and shape after a certain treatment strategy.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University Virginia
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Postdoctoral Fellow
        caption: May 2018 - Present
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            I work in the departments of Biomedical Engineering and Cardiovascular Medicine, where I lead a multidisciplinary team of engineers and clinicians to
            improve the outcome of cardiac resynchronization therapy. Besides my research responsibilities, I am priviliged to mentor several talented 
            undergraduate and graduate students, am a co-instructor of a biomechanics class, and am a founding board member of the Postdoctoral Association.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Eindhoven University of Technology
        caption: 2008 - 2018
        sub_title: BSc + MSc + PhD in Biomedical Engineering
        quote: >
          Mens agitat molem (The mind brings matter into motion)
        description: | # this will include new lines to allow paragraphs
          I obtained my degrees in biomedical engineering at the Eindhoven University of Technology, in the Netherlands.
          During my MSc and PhD degrees, I specialized in experimental and computational cardiovascular biomechanics and tissue engineering, resulting in 6 journal publications and a thesis  titled 'Growth and remodeling of native and engineered cardiovascular tissues'.

          As part of my training, I gained valuable educational and research experience at universities across the world:
          - **Stanford University** / Department of Mechanical Engineering (Visiting student researcher, 2016)
          - **University of Texas at Austin** / Center for Cardiovascular Modeling & Simulation (Graduate research assistant, 2012)
          - **Queen Mary, University of London** / Biomedical Engineering (Erasmus Scholar, 2010)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my professional interests, you can find me:
      - Riding my bike(s)
      - Bikepacking
      - Listing/playing music
      - Making pasta
      - Playing board games
      - Hanging out with my cats

      ![Playing music is fun](images/collage.jpg)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
